name: Playwright Java Tests with Allure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Install Playwright Browsers
        run: mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install"

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget
          wget https://github.com/allure-framework/allure2/releases/latest/download/allure-2.35.1.tgz -O allure.tgz
          mkdir -p $HOME/.allure
          tar -xvzf allure.tgz -C $HOME/.allure
          echo "$HOME/.allure/allure-2.35.1/bin" >> $GITHUB_PATH

      - name: Install Playwright dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwoff1 \
            libevent-2.1-7t64 \
            libgstreamer-plugins-base1.0-0 \
            libgstreamer-gl1.0-0 \
            libgstreamer-plugins-bad1.0-0 \
            libharfbuzz-icu0 \
            libsecret-1-0 \
            libhyphen0 \
            libmanette-0.2-0 \
            libgles2

      - name: Run tests
        run: mvn clean test -Dmaven.test.failure.ignore=true

      - name: Convert videos to mp4
        run: |
          mkdir -p target/videos_mp4
          for f in target/videos/*.webm; do
            name=$(basename "$f" .webm)
            ffmpeg -y -i "$f" -c:v libx264 -preset fast -crf 18 -r 30 -pix_fmt yuv420p "target/videos_mp4/$name.mp4"
          done

      - name: Generate Allure report
        run: |
          allure generate target/allure-results --clean -o target/allure-report

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target

      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: allure-report
